#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run format

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again. ❌';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo 'ESLint Check Failed. ❌'
    false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check. ❌'
    false;
)

# If everything passes... Now we can commit
echo 'Code looks good, Trying to build now. ✅'

npm run build ||
(
    echo 'Build Failed🔨❌'
    false;
)

# If everything passes... Now we can commit
echo 'Good Commit! ✅'